### ISSUE TITLE
Datepicker should set MS to start of second when selected.

### ISSUE THREAD

**Issue by wesbos** [joecohens/epoch#32]
Came across this today when our editor asked why the values differ every time he uses the date picker.

turns out selecting 7:00:00 leave the MS value to whatever it was when the page was loaded.

So - when someone selects a time, it should set the MS to `0000` since there is no MS input (and I don't think adding one would make sense?)

**Comment by joecohens** [comment]
This little tool need a bit of love so I've shipped a new upgraded version and fixed this issue on the way. Let me know if you still see it! 

https://github.com/joecohens/epoch/pull/33

**Comment by joecohens** [comment]
🙌
